name: build-test-XIOS

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test:
    name: build test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [XIOS/trunk@2252, XIOS2/trunk, XIOS3/trunk]
    steps:
      # Check out repository branch
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt -yq install subversion
            sudo apt -yq install $(<dependencies)
      - name: clone and build XIOS
        run: |
          svn co http://forge.ipsl.fr/ioserver/svn/${{ matrix.version }} XIOS
          cp arch/* XIOS/arch/
          cd XIOS
          if [ ${{ matrix.version }} == 'XIOS3/trunk' ]; then
            patch -p0 < ../patches/xios3/revert_svn2517_transport.patch
            sed -i 's/<variable_group id="parameters" >/<variable_group id="parameters" > <variable id="transport_protocol" type="string" >p2p<\/variable>/g' generic_testcase/iodef.xml
            cat generic_testcase/iodef.xml
          fi
          ./make_xios --job 2 --arch GCC_LINUX_APT --debug
          cd ..
        shell: bash
      - name: run generic
        run: |
          cd XIOS/generic_testcase
          ln -s ../bin/generic_testcase.exe
          ln -s ../bin/xios_server.exe
          sed -i 's/nb_proc_atm=4/nb_proc_atm=1/g' param.def
          mpiexec -n 1 ./generic_testcase.exe : -n 1 ./xios_server.exe
          cd ../..
      - name: run resample example
        run: |
          . arch/arch-GCC_LINUX_APT.env
          . arch/arch-GCC_LINUX_APT.path
          export XIOS_BINDIR=$PWD/XIOS/bin
          export XIOS_INCDIR=$PWD/XIOS/inc
          export XIOS_LIBDIR=$PWD/XIOS/lib

          export MVER=${{ matrix.version }}
          export MPI_FLAVOUR='openmpi'

          python3 -m unittest discover -v -s xios_examples
